Repository doldecomp/melee, pull requests merged in 2023-03, with the labels that each got.

#746 Fix editorconfig workflow
  .github/workflows/editorconfig.yml
Labels: tooling

#748 Improve editorconfig workflow QoL
  .github/workflows/editorconfig.yml
Labels: tooling

#749 Use `github.ref` instead of `github.head_ref` [skip editorconfig]
  .github/workflows/editorconfig.yml
Labels: tooling

#750 Revert `actions/checkout` ref
  .github/workflows/editorconfig.yml
Labels: tooling

#745 Add Windows build job and improve speed of Ubuntu build
  .github/workflows/build.yml
  Makefile
Labels: tooling

#743 Match `ftSeak_SpecialS`
  asm/melee/ft/chara/ftSeak/ftSeak_SpecialHi.s
  asm/melee/ft/chara/ftSeak/ftSeak_SpecialLw.s
  asm/melee/ft/chara/ftSeak/ftSeak_SpecialN.s
  asm/melee/ft/chara/ftSeak/ftSeak_SpecialS.s
  asm/melee/ft/chara/ftseak3.s
  obj_files.mk
  src/MetroTRK/intrinsics.h
  src/math.h
  src/melee/ft/chara/ftSeak/ftSeak_Init.c
  src/melee/ft/chara/ftSeak/ftSeak_Init.h
  src/melee/ft/chara/ftSeak/ftSeak_SpecialHi.c
  src/melee/ft/chara/ftSeak/ftSeak_SpecialHi.h
  src/melee/ft/chara/ftSeak/ftSeak_SpecialLw.c
  src/melee/ft/chara/ftSeak/ftSeak_SpecialLw.h
  src/melee/ft/chara/ftSeak/ftSeak_SpecialN.c
  src/melee/ft/chara/ftSeak/ftSeak_SpecialN.h
  src/melee/ft/chara/ftSeak/ftSeak_SpecialS.c
  src/melee/ft/chara/ftSeak/ftSeak_SpecialS.h
  src/melee/ft/chara/ftSeak/ftSeak_StateVars.h
  src/melee/ft/chara/ftSeak/ftseak.h
  src/melee/ft/chara/ftSeak/ftseak1.c
  src/melee/ft/chara/ftSeak/ftseak2.c
  src/melee/ft/chara/ftSeak/types.h
  src/melee/ft/chara/ftZelda/ftzelda4.c
  src/melee/ft/ftanim.h
  src/melee/ft/ftcommon.h
  src/melee/ft/ftdata1.c
  src/melee/ft/ftstatevars.h
  src/melee/ft/types.h
  src/melee/gr/grticeclimber.c
  src/melee/it/code_8027CF30.h
  src/sysdolphin/baselib/rumble.c
  src/sysdolphin/baselib/rumble.h
  tools/convert_data.py
  tools/m2ctx/README.md
Labels: do not squash

#752 Publish packages for building Melee and generating documentation
  .dockerignore
  .github/packages/build-linux/Dockerfile
  .github/packages/build-linux/entrypoint.sh
  .github/packages/build-linux/setup.sh
  .github/packages/build-windows/Dockerfile
  .github/packages/build-windows/entrypoint.ps1
  .github/packages/build-windows/setup.ps1
  .github/packages/gen-pages/Dockerfile
  .github/packages/gen-pages/entrypoint.sh
  .github/packages/gen-pages/setup.sh
  .github/workflows/build-melee.yml
  .github/workflows/build.yml
  .github/workflows/publish-packages.yml
  .github/workflows/publish-pages.yml
  .github/workflows/publish.yml
  Makefile
  tools/calcprogress/requirements.txt
  tools/calcprogress/src/requirements.txt
Labels: tooling

#754 Improve README instructions
  .github/README.md
Labels: documentation

#757 Fix cron jobs not pushing packages
  .github/workflows/publish-packages.yml
Labels: tooling

#762 Convert package names to lowercase
  .github/workflows/build-melee.yml
  .github/workflows/publish-packages.yml
  .github/workflows/publish-pages.yml
Labels: tooling

#756 Rewrite and improve `issues.sh`
  .cargo/config.toml
  .gitignore
  .rustfmt.toml
  Cargo.lock
  Cargo.toml
  tools/issues.sh
  tools/issues/Cargo.toml
  tools/issues/LICENSE
  tools/issues/src/main.rs
Labels: tooling

#759 Create flags parser CLI tool
  Cargo.lock
  Cargo.toml
  tools/flags/Cargo.toml
  tools/flags/LICENSE
  tools/flags/src/main.rs
Labels: tooling

#768 Match `func_8007C114`
  src/melee/ft/code_8007C114.c
  src/melee/ft/ft_unknown_006.h
Labels: scratch

#769 Add `dadosod` as a git subtree
  Cargo.lock
  Cargo.toml
  tools/dadosod/.gitignore
  tools/dadosod/Cargo.lock
  tools/dadosod/Cargo.toml
  tools/dadosod/LICENSE
  tools/dadosod/README.md
  tools/dadosod/src/doldisasm.rs
  tools/dadosod/src/lib.rs
  tools/dadosod/src/main.rs
  tools/dadosod/src/symbol.rs
  tools/dadosod/src/tracker.rs
  tools/dadosod/src/utils.rs
Labels: tooling, do not squash

#755 Update `split_suggester.py` to widen use cases
  requirements.txt
  tools/split_suggester.py
Labels: tooling

#770 Add `doxygen-awesome-css` as a git subtree
  .github/packages/gen-pages/entrypoint.sh
  .github/packages/gen-pages/setup.sh
  .gitignore
  tools/doxygen-awesome-css/.gitignore
  tools/doxygen-awesome-css/LICENSE
  tools/doxygen-awesome-css/doxygen-awesome-darkmode-toggle.js
  tools/doxygen-awesome-css/doxygen-awesome-fragment-copy-button.js
  tools/doxygen-awesome-css/doxygen-awesome-interactive-toc.js
  tools/doxygen-awesome-css/doxygen-awesome-paragraph-link.js
  tools/doxygen-awesome-css/doxygen-awesome-sidebar-only-darkmode-toggle.css
  tools/doxygen-awesome-css/doxygen-awesome-sidebar-only.css
  tools/doxygen-awesome-css/doxygen-awesome-tabs.js
  tools/doxygen-awesome-css/doxygen-awesome.css
  tools/doxygen-awesome-css/doxygen-custom/custom-alternative.css
  tools/doxygen-awesome-css/doxygen-custom/custom.css
  tools/doxygen-awesome-css/doxygen-custom/header.html
  tools/doxygen-awesome-css/doxygen-custom/toggle-alternative-theme.js
Labels: tooling, do not squash
