Repository doldecomp/melee, pull requests merged in 2024-01, with the labels that each got.

#1069 Create initial decomp-toolkit skeleton
  .editorconfig
  .gitattributes
  .gitignore
  config/GALE01/build.sha1
  config/GALE01/config.yml
  config/GALE01/splits.txt
  config/GALE01/symbols.txt
  configure.py
  orig/GALE01/.gitkeep
  tools/__init__.py
  tools/download_tool.py
  tools/ninja_syntax.py
  tools/project.py
  tools/transform_dep.py
  tools/upload_progress.py
Labels: tooling, do not squash

#1070 Move `orig/GALE01/.gitkeep` to `sys`
  .gitignore
  orig/GALE01/sys/.gitkeep
Labels: tooling

#1072 Disable `-W all` and fix include paths in `configure.py`
  configure.py
  src/sysdolphin/baselib/fobj.c
  src/sysdolphin/baselib/lobj.c
  src/sysdolphin/baselib/mobj.c
Labels: dtk

#1073 Synchronize `Makefile` and `configure.py` C flags
  Makefile
  configure.py
Labels: dtk

#1074 Add sample melee libs to `configure.py`
  config/GALE01/splits.txt
  config/GALE01/symbols.txt
  configure.py
  tools/project.py
Labels: dtk

#1078 Port `Makefile` options to `configure.py`
  configure.py
Labels: dtk

#1079 Port `obj_files.mk` to `configure.py`
  configure.py
Labels: dtk

#1081 Remove duplicate libs in `configure.py`
  configure.py
Labels: dtk

#1083 Improve symbol handling in `config-dtk`
  tools/config-dtk/src/main.rs
Labels: dtk

#1084 Split `cw_map` from `main` in `config-dtk`
  tools/config-dtk/src/cw_map.rs
  tools/config-dtk/src/main.rs
Labels: tooling, dtk

#1087 Parse `symbols.txt` in `config-dtk`
  Cargo.lock
  tools/config-dtk/Cargo.toml
  tools/config-dtk/src/cw_map.rs
  tools/config-dtk/src/dtk_config.rs
  tools/config-dtk/src/main.rs
Labels: tooling, dtk

#1088 Import symbol names and scopes from `GALE01.map` to `symbols.txt`
  config/GALE01/symbols.txt
  tools/config-dtk/src/cw_map.rs
  tools/config-dtk/src/dtk_config.rs
  tools/config-dtk/src/main.rs
Labels: tooling, dtk

#1089 Name some additional symbols in `symbols.txt`
  config/GALE01/symbols.txt
Labels: dtk

#1090 Create `decomp.py` as an abstraction over m2c
  .gitignore
  config/GALE01/symbols.txt
  tools/decomp.py
  tools/m2ctx/m2ctx.py
Labels: tooling

#1093 Commit `splits.todo.txt` for real
  config/GALE01/splits.todo.txt
Labels: dtk

#1094 Import nearly all splits into `splits.txt`
  config/GALE01/splits.todo.txt
  config/GALE01/splits.txt
  configure.py
Labels: dtk

#1095 Unlink `WIP` files in `configure.py`
  config/GALE01/splits.txt
  configure.py
Labels: dtk

#1096 Configure `asm-differ` for dtk
  tools/asm-differ/.github/workflows/black.yml
  tools/asm-differ/.github/workflows/check-poetry-lock.yml
  tools/asm-differ/.github/workflows/unit-tests.yml
  tools/asm-differ/.gitignore
  tools/asm-differ/.pre-commit-config.yaml
  tools/asm-differ/README.md
  tools/asm-differ/diff.py
  tools/asm-differ/diff_settings.py
  tools/asm-differ/mypy.ini
  tools/asm-differ/poetry.lock
  tools/asm-differ/test.py
Labels: tooling, do not squash, dtk

#1097 Update dtk template
  .gitignore
  tools/download_tool.py
  tools/ninja_syntax.py
  tools/project.py
  tools/transform_dep.py
  tools/upload_progress.py
Labels: do not squash, dtk

#1099 Unlink non-matching files in `configure.py`
  compile_flags.txt
  config/GALE01/splits.txt
  configure.py
  src/dolphin/os/OSAlloc.c
  src/melee/lb/lb_00B0.c
  src/sysdolphin/baselib/cobj.c
  src/sysdolphin/baselib/debug.h
  src/sysdolphin/baselib/mobj.c
  src/sysdolphin/baselib/tev.c
Labels: dtk

#1101 fix encoding and path issues on Windows in tools/decomp.py
  requirements.txt
  tools/decomp.py
  tools/m2ctx/m2ctx.py
Labels: tooling

#1103 fix path issues on Windows in tools/report_score.py
  tools/report_score.py
Labels: tooling

#1104 Disable `publish-pages`
  .github/workflows/publish-pages.yml
Labels: documentation

#1106 Fix `NOT_IMPLEMENTED` codegen in objdiff
  src/placeholder.h
Labels: dtk

#1107 Assume that `data:float` means size 4 in `symbols.txt`
  config/GALE01/symbols.txt
Labels: dtk

#1125 Update dtk to `v0.7.2`
  configure.py
Labels: dtk

#1126 Remove deprecated shell scripts
  tools/asmdiff.sh
  tools/build.sh
  tools/gen.sh
  tools/objdiff-make.sh
  tools/resync.sh
Labels: tooling

#1127 Remove `dadosod` subtree
  .github/packages/build-linux/Dockerfile
  .github/packages/dump-asm/entrypoint.sh
  Cargo.lock
  Cargo.toml
  tools/dadosod/.gitignore
  tools/dadosod/Cargo.toml
  tools/dadosod/LICENSE
  tools/dadosod/README.md
  tools/dadosod/src/doldisasm.rs
  tools/dadosod/src/lib.rs
  tools/dadosod/src/main.rs
  tools/dadosod/src/symbol.rs
  tools/dadosod/src/tracker.rs
  tools/dadosod/src/utils.rs
Labels: tooling

#1128 Remove deprecated rust tools
  Cargo.lock
  Cargo.toml
  tools/config-dtk/.idea/.gitignore
  tools/config-dtk/.idea/config.iml
  tools/config-dtk/.idea/modules.xml
  tools/config-dtk/.idea/vcs.xml
  tools/config-dtk/Cargo.lock
  tools/config-dtk/Cargo.toml
  tools/config-dtk/LICENSE
  tools/config-dtk/src/cw_map.rs
  tools/config-dtk/src/dtk_config.rs
  tools/config-dtk/src/main.rs
  tools/config-dtk/src/types.rs
  tools/diff-symbols/Cargo.toml
  tools/diff-symbols/LICENSE
  tools/diff-symbols/src/main.rs
  tools/fix-labels/Cargo.toml
  tools/fix-labels/LICENSE
  tools/fix-labels/src/main.rs
  tools/replace-module/Cargo.toml
  tools/replace-module/LICENSE
  tools/replace-module/src/main.rs
Labels: tooling

#1130 Remove deprecated Python tools
  tools/convert_data.py
  tools/dump_tree.py
  tools/frank.py
  tools/merge_double.py
  tools/mwld_patch.py
  tools/mwld_postpatch.sha1
  tools/mwld_prepatch.sha1
  tools/parse_map.py
  tools/postprocess.py
  tools/rename_symbols.py
Labels: tooling

#1131 Create `revert_asm.py` to unlink C files from `make`
  tools/revert_asm.py
Labels: tooling

#1129 Set mode `+x` on executable Python scripts
  configure.py
  tools/download_tool.py
  tools/find_include.py
  tools/split_suggester.py
  tools/transform_dep.py
  tools/upload_progress.py
Labels: tooling

#1137 Migrate to `pip-tools` for Python dependencies
  requirements.in
  requirements.txt
Labels: tooling

#1159 Update README
  .github/LEGACY_BUILD.md
  .github/README.md
  .github/assets/dolphin-extract.png
Labels: documentation

#1160 Add missing README section on diffing
  .github/README.md
  .github/assets/objdiff.png
Labels: documentation

#1163 Add objdiff option tip to README
  .github/README.md
  .github/assets/relax.png
Labels: documentation
